const SUPABASE_URL='https://qgkrwfwhweqyzlzgwair.supabase.co';
const SUPABASE_KEY='sb_publishable_caoCyu6MQc5R_-4t4qGE3A_z23R4rYh';
const db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const IDS=['H1','H2','H3','S1','S2','S3'];
const QF=[[1,8],[4,5],[2,7],[3,6]];
let settings=null,bowlers=[],brackets={},history=[],selected='H1',currentView='setup';
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];

function toast(msg){const t=$('#toast');t.textContent=msg;t.hidden=false;clearTimeout(window._tt);window._tt=setTimeout(()=>t.hidden=true,2600)}
function money(v){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0))}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function blankState(){return {entrants:[],manualWinners:{},champion:null}}
function ensureState(b){const s=b.state&&typeof b.state==='object'?b.state:blankState();s.entrants=Array.isArray(s.entrants)?s.entrants:[];s.manualWinners=s.manualWinners||{};return s}
function hdcp(avg){if(!settings||selected.startsWith('S'))return 0;const raw=Math.max(0,(Number(settings.handicap_base)-Number(avg||0))*Number(settings.handicap_percent));return settings.handicap_rounding==='CEIL'?Math.ceil(raw):settings.handicap_rounding==='ROUND'?Math.round(raw):Math.floor(raw)}
function bySeed(b,seed){return ensureState(b).entrants.find(e=>Number(e.seed)===Number(seed))||null}
function score(e,g){const v=e?.[`g${g}`];return v===''||v===null||v===undefined?null:Number(v)}
function total(b,e,g){const s=score(e,g);if(s===null)return null;return s+(b.type==='Handicap'?Number(e.handicap||0):0)}
function decide(b,a,c,g,key){if(!a||!c)return null;const sa=score(a,g),sc=score(c,g);if(sa===null||sc===null)return null;const ta=total(b,a,g),tc=total(b,c,g);if(ta>tc)return a;if(tc>ta)return c;if(b.type==='Handicap'){if(sa>sc)return a;if(sc>sa)return c}const m=ensureState(b).manualWinners?.[key];if(m)return [a,c].find(x=>x.slot===m)||null;return 'TIE'}
function calcBracket(b){const q=QF.map((p,i)=>{const a=bySeed(b,p[0]),c=bySeed(b,p[1]);return {key:`q${i+1}`,a,c,w:decide(b,a,c,1,`q${i+1}`)}});const s1={key:'s1',a:q[0].w&&q[0].w!=='TIE'?q[0].w:null,c:q[1].w&&q[1].w!=='TIE'?q[1].w:null};s1.w=decide(b,s1.a,s1.c,2,'s1');const s2={key:'s2',a:q[2].w&&q[2].w!=='TIE'?q[2].w:null,c:q[3].w&&q[3].w!=='TIE'?q[3].w:null};s2.w=decide(b,s2.a,s2.c,2,'s2');const f={key:'f',a:s1.w&&s1.w!=='TIE'?s1.w:null,c:s2.w&&s2.w!=='TIE'?s2.w:null};f.w=decide(b,f.a,f.c,3,'f');return {q,s:[s1,s2],f,champion:f.w&&f.w!=='TIE'?f.w:null}}

async function init(){const {data:{session}}=await db.auth.getSession();bind();if(session)await enterApp();else showAuth();db.auth.onAuthStateChange(async(_e,s)=>{if(s)await enterApp();else showAuth()})}
function bind(){
 $('#loginForm').addEventListener('submit',login);$('#signOutBtn').onclick=()=>db.auth.signOut();
 $$('.tab').forEach(b=>b.onclick=()=>setView(b.dataset.view));
 $('#saveSettingsBtn').onclick=saveSettings;$('#saveEntrantsBtn').onclick=saveEntrants;$('#randomizeBtn').onclick=()=>randomize(selected);$('#randomizeAllBtn').onclick=randomizeAll;$('#openLiveBtn').onclick=()=>setView('live');$('#resetBracketBtn').onclick=()=>resetBracket(selected);$('#resetNightBtn').onclick=resetNight;$('#refreshHistoryBtn').onclick=loadHistory;
}
async function login(e){e.preventDefault();const email=$('#loginEmail').value.trim();$('#loginStatus').textContent='Sending link…';const redirect=window.location.origin+window.location.pathname;const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:redirect}});$('#loginStatus').textContent=error?error.message:'Check your email for the sign-in link.'}
function showAuth(){ $('#authScreen').hidden=false;$('#app').hidden=true }
async function enterApp(){try{await loadAll();$('#authScreen').hidden=true;$('#app').hidden=false;renderAll()}catch(e){console.error(e);$('#loginStatus').textContent='Signed in, but this email is not authorized for this app yet.';$('#authScreen').hidden=false;$('#app').hidden=true}}
async function loadAll(){const [s,b,br,h]=await Promise.all([db.from('app_settings').select('*').eq('id',1).single(),db.from('bowlers').select('*').order('name'),db.from('brackets').select('*'),db.from('bracket_history').select('*').order('completed_at',{ascending:false}).limit(100)]);for(const x of [s,b,br,h])if(x.error)throw x.error;settings=s.data;bowlers=b.data||[];brackets=Object.fromEntries((br.data||[]).map(x=>[x.id,x]));history=h.data||[]}
async function loadHistory(){const {data,error}=await db.from('bracket_history').select('*').order('completed_at',{ascending:false}).limit(100);if(error)return toast(error.message);history=data||[];renderResults()}
function renderAll(){renderHeader();renderPicker();renderSetup();renderLive();renderResults();setView(currentView)}
function renderHeader(){$('#appTitle').textContent=settings.app_title;$('#seasonLine').textContent=`${settings.season} • Week ${settings.league_week} • ${Math.round(Number(settings.handicap_percent)*100)}% of ${settings.handicap_base}`}
function renderPicker(){const el=$('#bracketPicker');el.innerHTML=IDS.map(id=>`<button class="bracket-btn ${id===selected?'active':''} ${brackets[id]?.active?'':'inactive'}" data-id="${id}">${id}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.id;renderAll()})}
function setView(v){currentView=v;$$('.tab').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('#setupView').hidden=v!=='setup';$('#liveView').hidden=v!=='live';$('#resultsView').hidden=v!=='results';if(v==='live')renderLive();if(v==='results')renderResults()}
function renderSetup(){const b=brackets[selected];if(!b)return;const st=ensureState(b);$('#setupBracketTitle').textContent=`${b.id} • ${b.type}`;$('#activeToggle').checked=b.active;$('#seasonInput').value=settings.season;$('#weekInput').value=settings.league_week;$('#feeInput').value=settings.entry_fee;$('#baseInput').value=settings.handicap_base;$('#percentInput').value=settings.handicap_percent;$('#roundingInput').value=settings.handicap_rounding;$('#bowlerList').innerHTML=bowlers.filter(x=>x.active).map(x=>`<option value="${esc(x.name)}" data-average="${x.average??''}"></option>`).join('');
 const rows=[];for(let i=1;i<=8;i++){const e=st.entrants.find(x=>x.slot===i)||{slot:i,name:'',average:'',paid:false};rows.push(`<div class="entrant-row"><div class="slot">${i}</div><label>Name<input class="name-input" list="bowlerList" data-slot="${i}" value="${esc(e.name||'')}" ${b.randomized?'disabled':''}></label><label>Avg<input class="avg-input" data-slot="${i}" type="number" inputmode="numeric" min="0" max="300" value="${e.average??''}" ${b.randomized?'disabled':''}>${b.type==='Handicap'&&e.name?`<span class="hdcp-pill">HDCP ${e.handicap??hdcp(e.average)}</span>`:''}</label><label>Paid<div class="paid-wrap"><input class="paid-input" data-slot="${i}" type="checkbox" ${e.paid?'checked':''}></div></label></div>`)}$('#entrantRows').innerHTML=rows.join('');
 $$('.name-input').forEach(inp=>inp.addEventListener('change',()=>{const found=bowlers.find(x=>x.name.toLowerCase()===inp.value.trim().toLowerCase());if(found){const avg=$(`.avg-input[data-slot="${inp.dataset.slot}"]`);if(!avg.value)avg.value=found.average??''}}));$$('.paid-input').forEach(inp=>inp.onchange=()=>quickPaid(Number(inp.dataset.slot),inp.checked));$('#randomizeBtn').disabled=b.randomized;$('#saveEntrantsBtn').disabled=b.randomized}
async function saveSettings(){const payload={season:Number($('#seasonInput').value),league_week:Number($('#weekInput').value),entry_fee:Number($('#feeInput').value),handicap_base:Number($('#baseInput').value),handicap_percent:Number($('#percentInput').value),handicap_rounding:$('#roundingInput').value};const {data,error}=await db.from('app_settings').update(payload).eq('id',1).select().single();if(error)return toast(error.message);settings=data;for(const b of Object.values(brackets)){if(b.type==='Handicap'&&!b.randomized){const st=ensureState(b);st.entrants.forEach(e=>e.handicap=calcHdcpFor(e.average,payload));await db.from('brackets').update({state:st}).eq('id',b.id)}}toast('Settings saved');await loadAll();renderAll()}
function calcHdcpFor(avg,s=settings){const raw=Math.max(0,(Number(s.handicap_base)-Number(avg||0))*Number(s.handicap_percent));return s.handicap_rounding==='CEIL'?Math.ceil(raw):s.handicap_rounding==='ROUND'?Math.round(raw):Math.floor(raw)}
async function saveEntrants(){const b=brackets[selected];const names=$$('.name-input').map(x=>x.value.trim()).filter(Boolean);if(new Set(names.map(x=>x.toLowerCase())).size!==names.length)return toast('A bowler can only appear once in the same bracket.');const entrants=[];for(let i=1;i<=8;i++){const name=$(`.name-input[data-slot="${i}"]`).value.trim(),avgRaw=$(`.avg-input[data-slot="${i}"]`).value,paid=$(`.paid-input[data-slot="${i}"]`).checked;if(!name)continue;const average=Number(avgRaw);if(!Number.isFinite(average)||average<0||average>300)return toast(`Enter a valid average for ${name}.`);entrants.push({slot:i,name,average,handicap:b.type==='Handicap'?calcHdcpFor(average):0,paid,seed:null,g1:null,g2:null,g3:null})}
 const state={entrants,manualWinners:{},champion:null};const {error}=await db.from('brackets').update({active:$('#activeToggle').checked,state,randomized:false,archived:false}).eq('id',selected);if(error)return toast(error.message);if(entrants.length){const up=entrants.map(e=>({name:e.name,average:e.average,active:true}));await db.from('bowlers').upsert(up,{onConflict:'name'})}toast('Entrants saved');await loadAll();renderAll()}
async function quickPaid(slot,paid){const b=brackets[selected],st=ensureState(b),e=st.entrants.find(x=>x.slot===slot);if(!e)return;e.paid=paid;const {error}=await db.from('brackets').update({state:st}).eq('id',selected);if(error)toast(error.message);else{b.state=st;renderResults()}}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function randomize(id){const b=brackets[id],st=ensureState(b);if(st.entrants.length!==8)return toast(`${id} needs exactly 8 bowlers.`);const seeds=shuffle([1,2,3,4,5,6,7,8]);st.entrants.forEach((e,i)=>{e.seed=seeds[i];e.g1=null;e.g2=null;e.g3=null});st.manualWinners={};st.champion=null;const {error}=await db.from('brackets').update({active:true,randomized:true,archived:false,state:st}).eq('id',id);if(error)return toast(error.message);toast(`${id} randomized`);await loadAll();renderAll()}
async function randomizeAll(){for(const id of IDS){const b=brackets[id];if(b.active&&!b.randomized&&ensureState(b).entrants.length===8)await randomize(id)}toast('Active brackets randomized')}
async function resetBracket(id){if(!confirm(`Reset ${id}? This clears entrants and scores for this bracket.`))return;const {error}=await db.from('brackets').update({active:false,randomized:false,archived:false,state:blankState()}).eq('id',id);if(error)return toast(error.message);await loadAll();renderAll();toast(`${id} reset`)}
async function resetNight(){if(!confirm('Reset the entire night? This clears all six current brackets. History stays saved.'))return;for(const id of IDS)await db.from('brackets').update({active:false,randomized:false,archived:false,state:blankState()}).eq('id',id);await loadAll();renderAll();toast('Night reset')}
function renderLive(){const b=brackets[selected];if(!b)return;const el=$('#liveContent');if(!b.randomized){el.innerHTML=`<div class="card empty"><strong>${b.id} is not randomized yet.</strong><br><span>Set up 8 bowlers, then randomize.</span></div>`;return}const calc=calcBracket(b);let html='';if(calc.champion)html+=`<div class="champion-card"><div class="trophy">🏆</div><div class="muted">${b.id} Champion</div><h2>${esc(calc.champion.name)}</h2></div>`;html+=`<div class="round-title">Game 1 • Quarterfinals</div>${calc.q.map(m=>matchHtml(b,m,1)).join('')}<div class="round-title">Game 2 • Semifinals</div>${calc.s.map(m=>matchHtml(b,m,2)).join('')}<div class="round-title">Game 3 • Championship</div>${matchHtml(b,calc.f,3)}`;el.innerHTML=html;el.querySelectorAll('.score-input').forEach(inp=>inp.onchange=()=>saveScore(Number(inp.dataset.slot),Number(inp.dataset.game),inp.value));el.querySelectorAll('[data-manual]').forEach(btn=>btn.onclick=()=>manualWinner(btn.dataset.key,Number(btn.dataset.manual)));archiveIfComplete(b,calc)}
function playerHtml(b,e,g,w){if(!e)return `<div class="player"><div><div class="player-name">Waiting…</div></div><input class="score-input" disabled placeholder="—"></div>`;const s=score(e,g),t=total(b,e,g);const result=w&&w!=='TIE'?(w.slot===e.slot?'winner':'loser'):'';const meta=b.type==='Handicap'?`Avg ${e.average} • HDCP ${e.handicap}${s!==null?` • Total ${t}`:''}`:`Avg ${e.average}`;return `<div class="player ${result}"><div><div class="player-name">${e.seed?`#${e.seed} `:''}${esc(e.name)} ${e.paid?'':'<span style="color:#b91c1c;font-size:.72rem">UNPAID</span>'}</div><div class="player-meta">${meta}</div></div><input class="score-input" data-slot="${e.slot}" data-game="${g}" type="number" inputmode="numeric" min="0" max="300" value="${s??''}" placeholder="Score"></div>`}
function matchHtml(b,m,g){let h=`<div class="match">${playerHtml(b,m.a,g,m.w)}${playerHtml(b,m.c,g,m.w)}`;if(m.w==='TIE'&&m.a&&m.c)h+=`<div class="tie-box"><p>Exact tie — choose the winner.</p><div class="tie-actions"><button class="btn ghost" data-key="${m.key}" data-manual="${m.a.slot}">${esc(m.a.name)}</button><button class="btn ghost" data-key="${m.key}" data-manual="${m.c.slot}">${esc(m.c.name)}</button></div></div>`;return h+'</div>'}
async function saveScore(slot,g,val){if(val==='')return;const n=Number(val);if(!Number.isInteger(n)||n<0||n>300)return toast('Scores must be whole numbers from 0 to 300.');const b=brackets[selected],st=ensureState(b),e=st.entrants.find(x=>x.slot===slot);if(!e)return;e[`g${g}`]=n;for(const key of Object.keys(st.manualWinners||{}))delete st.manualWinners[key];const {error}=await db.from('brackets').update({state:st,archived:false}).eq('id',selected);if(error)return toast(error.message);b.state=st;b.archived=false;renderLive();renderResults()}
async function manualWinner(key,slot){const b=brackets[selected],st=ensureState(b);st.manualWinners[key]=slot;const {error}=await db.from('brackets').update({state:st,archived:false}).eq('id',selected);if(error)return toast(error.message);b.state=st;b.archived=false;renderLive()}
async function archiveIfComplete(b,calc){if(!calc.champion||b.archived)return;const runner=calc.f.a?.slot===calc.champion.slot?calc.f.c:calc.f.a;const st=ensureState(b),paid=st.entrants.filter(e=>e.paid).length;const row={season:settings.season,league_week:settings.league_week,bracket_id:b.id,type:b.type,champion:calc.champion.name,runner_up:runner?.name||null,entrants:st.entrants.length,paid_entries:paid,entry_fee:Number(settings.entry_fee),collected:paid*Number(settings.entry_fee),state:st};const {error}=await db.from('bracket_history').upsert(row,{onConflict:'season,league_week,bracket_id'});if(error){console.error(error);return}await db.from('brackets').update({archived:true,state:{...st,champion:calc.champion.name}}).eq('id',b.id);b.archived=true;loadHistory()}
function renderResults(){const tonight=IDS.map(id=>brackets[id]).filter(Boolean);const paid=tonight.reduce((n,b)=>n+ensureState(b).entrants.filter(e=>e.paid).length,0);const entered=tonight.reduce((n,b)=>n+ensureState(b).entrants.length,0);const complete=tonight.filter(b=>b.randomized&&calcBracket(b).champion).length;let html=`<div class="summary-grid"><div class="stat"><strong>${entered}</strong><span>Entries</span></div><div class="stat"><strong>${paid}</strong><span>Paid</span></div><div class="stat"><strong class="money">${money(paid*Number(settings.entry_fee))}</strong><span>Collected</span></div></div>`;html+='<div class="card"><h2>Tonight</h2>';for(const b of tonight){const st=ensureState(b),c=b.randomized?calcBracket(b).champion:null;html+=`<div class="history-row"><div><strong>${b.id} • ${b.type}</strong><span>${c?`Champion: ${esc(c.name)}`:b.randomized?'In progress':b.active?'Ready':'Inactive'}</span></div><div><strong>${st.entrants.filter(e=>e.paid).length}/${st.entrants.length}</strong><span>paid</span></div></div>`}html+='</div>';$('#resultsSummary').innerHTML=html;$('#historyList').innerHTML=history.length?history.map(h=>`<div class="history-row"><div><strong>${h.bracket_id} • ${esc(h.champion||'—')}</strong><span>${h.season} Week ${h.league_week} • Runner-up ${esc(h.runner_up||'—')}</span></div><div><strong>${money(h.collected)}</strong><span>${h.paid_entries} paid</span></div></div>`).join(''):'<div class="empty">No completed brackets yet.</div>'}

init();